- hosts: localhost
  connection: local
  vars_files:
    - vars.yml
  vars_prompt:
    - name: do_name
      prompt: "Name of server"
      private: no
    - name: do_dns
      prompt: "DNS name to bind(optional)"
      private: no
  tasks:
    - name: Register SSH key
      digital_ocean: >
        state=present
        command=ssh
        name="{{ do_ssh_name }}"
        ssh_pub_key="{{ do_ssh_pub_key }}"
        api_token={{ do_api_token }}
      register: do_droplet

    - name: Register Droplet
      digital_ocean: >
        state=active
        command=droplet
        name={{ do_name }}
        region_id={{ do_region }}
        size_id={{ do_size }}
        image_id={{ do_image }}
        ssh_key_ids={{ do_droplet.ssh_key.id }}
        unique_name=yes
        api_token={{ do_api_token }}
        wait_timeout=600
      register: do_droplet

    - name: Register DNS
      digital_ocean_domain: >
        state=present
        name="{{ do_dns }}"
        id="{{ do_droplet.droplet.id }}"
        api_token={{ do_api_token }}
      when: do_dns|length > 0

    - debug: msg="IP is {{ do_droplet.droplet.ip_address }}"

    - name: Add new droplet to inventory
      add_host: >
        name="{{ do_name }}"
        groups=dohosts
        ansible_ssh_host="{{ do_droplet.droplet.ip_address }}"
        ansible_ssh_user=root
        ansible_ssh_private_key_file="{{ do_ssh_private_key }}"


- hosts: dohosts
  remote_user: root
  gather_facts: no
  pre_tasks:
    - name: 'Install python'
      raw: apt-get -y install python-simplejson
  vars_files:
      - vars.yml
  tasks:
    - include: tasks/swap.yml
    - include: tasks/user.yml
    - include: tasks/security.yml
    - include: tasks/tools.yml
  handlers:
    - include: handlers/base.yml
    