- name: Strict SSH access
  lineinfile: >
    dest=/etc/ssh/sshd_config
    state=present
    regexp='^#?{{ item.key }}'
    line='{{ item.key }} {{ item.value }}'
    validate='/usr/sbin/sshd -t -f %s'
  with_items:
    - { key: 'PermitRootLogin',        value: 'no'}
    - { key: 'PasswordAuthentication', value: 'no'}
    - { key: 'AllowGroups',            value: '{{ ssh_groups }}' }
    - { key: 'MaxAuthTries',           value: "5"}
    - { key: 'LoginGraceTime',         value: "60"}
    - { key: 'MaxSessions',            value: "5"}
    - { key: 'MaxStartups',            value: "10:30:60"}
    - { key: 'Port',                   value: '{{ ssh_port }}' }
  notify: restart sshd

- name: Configure firewall for SSH
  ufw: rule=allow port={{ item }}
  with_items: "{{ ufw_allow_ports }}"

- name: Enable firewall
  ufw: state=enabled